runtime: python310

beta_settings:
  cloud_sql_instances: adgest:europe-west1:db-adgest2

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "…"
  DATABASE_URL: "mysql+pymysql://db_adgest2:Sporting789%3F@/adgest_db?unix_socket=/cloudsql/adgest:europe-west1:db-adgest2"
entrypoint: gunicorn -b :$PORT run:app
