"""Adiciona numero_cliente ao DocumentoContabilistico

Revision ID: da16a8fffe20
Revises: 371c69182362
Create Date: 2025-03-31 13:09:18.767632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da16a8fffe20'
down_revision = '371c69182362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_cliente', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_column('numero_cliente')

    # ### end Alembic commands ###
