"""Adiciona tabelas de histórico e comentários

Revision ID: 14e7cffeecff
Revises: d3ff5550c93c
Create Date: 2025-04-08 01:11:13.452436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e7cffeecff'
down_revision = 'd3ff5550c93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assuntos_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assunto_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shared_tarefas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    op.create_table('shared_tarefas',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('tarefa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas.id'], name='fk_shared_tarefas_tarefa_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_shared_tarefas_user_id', ondelete='CASCADE')
    )
    op.drop_table('comments')
    op.drop_table('assuntos_history')
    # ### end Alembic commands ###
