"""recreae accounting

Revision ID: 33a3173cc117
Revises: d9a55be00293
Create Date: 2025-05-18 16:47:15.700832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a3173cc117'
down_revision = 'd9a55be00293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.create_index('idx_doc_data_emissao', ['data_emissao'], unique=False)
        batch_op.create_index('idx_doc_data_vencimento', ['data_vencimento'], unique=False)
        batch_op.create_index('idx_doc_status', ['status_cobranca'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_index('idx_doc_status')
        batch_op.drop_index('idx_doc_data_vencimento')
        batch_op.drop_index('idx_doc_data_emissao')

    op.drop_table('tmp_documento')
    # ### end Alembic commands ###
