"""recreate accounting2

Revision ID: 500593a24ff5
Revises: 33a3173cc117
Create Date: 2025-05-18 17:08:50.810278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500593a24ff5'
down_revision = '33a3173cc117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FATURA', 'DESPESA', name='doc_tipo'),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status_cobranca',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDENTE', 'PAGA', 'TENTATIVA_COBRANCA', 'EM_TRIBUNAL', 'INCOBRAVEL', name='status_cobranca'),
               existing_nullable=True)
        batch_op.create_index('idx_user_status', ['user_id', 'status_cobranca'], unique=False)
        batch_op.create_unique_constraint('uq_cliente_tipo_numero', ['client_id', 'tipo', 'numero'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cliente_tipo_numero', type_='unique')
        batch_op.drop_index('idx_user_status')
        batch_op.alter_column('status_cobranca',
               existing_type=sa.Enum('PENDENTE', 'PAGA', 'TENTATIVA_COBRANCA', 'EM_TRIBUNAL', 'INCOBRAVEL', name='status_cobranca'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('FATURA', 'DESPESA', name='doc_tipo'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
