"""Cria tabelas iniciais

Revision ID: 820513345a26
Revises: b67186c02ed5
Create Date: 2025-04-13 22:27:58.664640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820513345a26'
down_revision = 'b67186c02ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    # ### end Alembic commands ###
