"""Adiciona tabelas de histórico e comentários

Revision ID: b67186c02ed5
Revises: e9304f02e74b
Create Date: 2025-04-08 23:49:49.323410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67186c02ed5'
down_revision = 'e9304f02e74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prazos_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prazo_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prazos_history')
    # ### end Alembic commands ###
