"""Adiciona tabelas de histórico para assuntos e tarefas

Revision ID: cb3398bac0b8
Revises: 14e7cffeecff
Create Date: 2025-04-08 01:38:10.236459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3398bac0b8'
down_revision = '14e7cffeecff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas_history')
    # ### end Alembic commands ###
