"""shared clients e auth

Revision ID: e29b1674e490
Revises: 500593a24ff5
Create Date: 2025-05-21 22:30:45.313254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29b1674e490'
down_revision = '500593a24ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_shares', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_shares', schema=None) as batch_op:
        batch_op.alter_column('option',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
