"""Adiciona campo advogado ao modelo DocumentoContabilistico

Revision ID: 371c69182362
Revises: 4d58c7150b24
Create Date: 2025-03-29 03:51:58.636135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371c69182362'
down_revision = '4d58c7150b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advogado', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_column('advogado')

    # ### end Alembic commands ###
