"""Adiciona campo numero em DocumentoContabilistico

Revision ID: 4d58c7150b24
Revises: e40b8df53b15
Create Date: 2025-03-29 03:39:03.362815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d58c7150b24'
down_revision = 'e40b8df53b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_column('numero')

    # ### end Alembic commands ###
