"""Adiciona data_emissao ao DocumentoContabilistico

Revision ID: e40b8df53b15
Revises: f885c7a04f9a
Create Date: 2025-03-29 01:20:01.696863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40b8df53b15'
down_revision = 'f885c7a04f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_emissao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_column('data_emissao')

    # ### end Alembic commands ###
