"""Adiciona data_vencimento ao modelo DocumentoContabilistico

Revision ID: f885c7a04f9a
Revises: ed57b610a7e7
Create Date: 2025-03-29 01:10:35.005305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f885c7a04f9a'
down_revision = 'ed57b610a7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_contabilisticos', schema=None) as batch_op:
        batch_op.drop_column('data_vencimento')

    # ### end Alembic commands ###
