"""Altera restrição única para clientes

Revision ID: 07d90978db96
Revises: b5cff13a7bc2
Create Date: 2025-03-18 15:04:06.232574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d90978db96'
down_revision = 'b5cff13a7bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_clientname', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_clientname', type_='unique')

    # ### end Alembic commands ###
