"""empty message

Revision ID: 3e3eefb18ff0
Revises: 19f7c6c672f1
Create Date: 2025-03-16 23:02:01.101660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3eefb18ff0'
down_revision = '19f7c6c672f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_clients',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('shared_tarefas',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_tarefas')
    op.drop_table('shared_clients')
    # ### end Alembic commands ###
